pref('extensions.firefox-muter.firstRun', true);
pref('extensions.firefox-muter.shortcut.key', 'M');
pref('extensions.firefox-muter.shortcut.modifiers', 'control alt');
pref('extensions.firefox-muter.showInAddonBar', true);
pref('extensions.firefox-muter.showInStatusBar', false);
pref('extensions.firefox-muter.skin.updateurl', 'http://feedback.firefox.com.cn/muter/skin.json');
pref('extensions.firefox-muter.disabledIcon', 'chrome://muter/skin/mute-disabled.png');
pref('extensions.firefox-muter.enabledIcon', 'chrome://muter/skin/mute-enabled.png');
pref('extensions.firefox-muter.switchButtonType', 'menu-button');
pref('extensions.firefox-muter.feedbackUrl', 'http://feedback.firefox.com.cn/muter/feedback.php');
pref('extensions.firefox-muter.saveStatus', false);
pref('extensions.firefox-muter.muteStatus', false);
pref('extensions.firefox-muter.disabledIcon.default', 'chrome://muter/skin/mute-disabled.png');
pref('extensions.firefox-muter.enabledIcon.default', 'chrome://muter/skin/mute-enabled.png');
