pref('extensions.firefox-muter.firstRun', true);
pref('extensions.firefox-muter.shortcut.key', 'M');
pref('extensions.firefox-muter.shortcut.modifiers', 'control shift');
pref('extensions.firefox-muter.showInAddonBar', true);
pref('extensions.firefox-muter.skin.updateurl', 'http://www.yxl.name/Firefox-Muter/www/update/skin.json');
pref('extensions.firefox-muter.disabledIcon', 'chrome://muter/skin/mute-disabled.png');
pref('extensions.firefox-muter.enabledIcon', 'chrome://muter/skin/mute-enabled.png');
pref('extensions.firefox-muter.switchButtonType', 'menu-button');
pref('extensions.firefox-muter.feedbackUrl', 'http://www.yxl.name/Firefox-Muter/www/feedback.php');
pref('extensions.firefox-muter.saveStatus', false);
pref('extensions.firefox-muter.muteStatus', false);
pref('extensions.firefox-muter.disabledIcon.default', 'chrome://muter/skin/mute-disabled.png');
pref('extensions.firefox-muter.enabledIcon.default', 'chrome://muter/skin/mute-enabled.png');
